POST http://localhost:3000/users/
Content-Type: application/json

{
  "user": {
    "email": "mailme1@gmail.com",
    "password": "Password1",
    "name": "Test User1"
  }
}

###
POST http://localhost:3000/users/
Content-Type: application/json

{
  "user": {
    "email": "mailme2@gmail.com",
    "password": "Password2",
    "name": "Test User2"
  }
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "user": {
    "email": "mailme1@gmail.com",
    "password": "Password1"
  }
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "user": {
    "email": "mailme2@gmail.com",
    "password": "Password2"
  }
}
###
GET http://localhost:3000/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNzU2MmIwODktZDA0Ny00MWFlLThkNDQtYTc5YWM1OTNhOWVmIiwiZW1haWwiOiJtYWlsbWUxQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGdZZThpQnlJbXl5ZEtRM1hRNkJ1T2VTcy4xdTdpc3NDSlFMTU5ORzVhaFFiTmxQU3BRLkRLIiwibmFtZSI6IlRlc3QgVXNlcjEiLCJ1cGRhdGVkQXQiOiIyMDIyLTAxLTMxVDEzOjMwOjIwLjU3NVoiLCJjcmVhdGVkQXQiOiIyMDIyLTAxLTMxVDEzOjMwOjIwLjU3NVoifSwiaWF0IjoxNjQzNjM1ODIwfQ.o4rJml0r9AvLMYXecUsGPdjkPKA99m3i9jv-kbfu4AU
###