POST http://localhost:3000/users/
Content-Type: application/json

{
  "user": {
    "email": "mailme1@gmail.com",
    "password": "Password1",
    "name": "Test User1"
  }
}

###
POST http://localhost:3000/users/
Content-Type: application/json

{
  "user": {
    "email": "mailme2@gmail.com",
    "password": "Password2",
    "name": "Test User2"
  }
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "user": {
    "email": "mailme1@gmail.com",
    "password": "Password1"
  }
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "user": {
    "email": "mailme2@gmail.com",
    "password": "Password2"
  }
}
###
GET http://localhost:3000/users/
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiZDI0ZGFhMzEtZGEzYy00ZGZkLTliZmItOWEwNDc3OTBjOWRmIiwiZW1haWwiOiJtYWlsbWUyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHRicEs5Q3RHLmw5dXRzTmprbExja2VtVDYvRmxBVHlsdi5CaTFMQm03MTl4VDJ6VjhsSm1pIiwibmFtZSI6IlRlc3QgVXNlcjIiLCJ1cGRhdGVkQXQiOiIyMDIyLTAxLTMxVDA5OjM4OjAwLjkyOVoiLCJjcmVhdGVkQXQiOiIyMDIyLTAxLTMxVDA5OjM4OjAwLjkyOVoifSwiaWF0IjoxNjQzNjIxODgwfQ.8_cSMpn3uKrD1nzXT5szWfiqKh3601iIzbC9TVQJX-o
###
POST http://localhost:3000/tickets/
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiZDI0ZGFhMzEtZGEzYy00ZGZkLTliZmItOWEwNDc3OTBjOWRmIiwiZW1haWwiOiJtYWlsbWUyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHRicEs5Q3RHLmw5dXRzTmprbExja2VtVDYvRmxBVHlsdi5CaTFMQm03MTl4VDJ6VjhsSm1pIiwibmFtZSI6IlRlc3QgVXNlcjIiLCJ1cGRhdGVkQXQiOiIyMDIyLTAxLTMxVDA5OjM4OjAwLjkyOVoiLCJjcmVhdGVkQXQiOiIyMDIyLTAxLTMxVDA5OjM4OjAwLjkyOVoifSwiaWF0IjoxNjQzNjIxODgwfQ.8_cSMpn3uKrD1nzXT5szWfiqKh3601iIzbC9TVQJX-o

Content-Type: application/json
{
    "ticket": {
        "category": "asset",
        "subcategory": "requestAllocation",
        "title": "Allocate Sample Asset",
        "description": "Need sample asset for productive work",
        "assignedTo": "a179d357-3234-43ad-984e-594f82895fd8"
    }
}